plugins {
    id "com.github.node-gradle.node" version '7.1.0'
    id 'com.enonic.defaults' version '2.1.6'
    id 'com.enonic.xp.app'
    id 'maven-publish'
}

node {
    download = true
    version = '20.9.0'
}

dependencies {
    implementation xplibs.api.portal
    include xplibs.portal
    include xplibs.node
    include xplibs.value
    include xplibs.repo
    include xplibs.context
    include libs.lib.mustache
    include libs.lib.router
}

repositories {
    mavenLocal()
    mavenCentral()
    xp.enonicRepo()
}

task webpack(type: NodeTask) {
    script = file('node_modules/webpack/bin/webpack.js')
}

// processes your package.json before running webpack
webpack.dependsOn 'npmInstall'
webpack.dependsOn 'processResources'

jar.dependsOn webpack
